
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argo-git
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: test1
  project: default
  source:
    repoURL: https://github.com/mguletskii/argo_image_updater.git
    targetRevision: main
    path: overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
